server:
  port: 8083
  servlet:
    context-path: /rfid-emu-service
  forward-headers-strategy: framework

spring:
  application:
    name: rfid-emu-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      retries: 3
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS:localhost:9094}
    properties:
      retry-backoff-ms: 1000
      enable-idempotence: true
      max-in-flight-request-per-connection: 1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs