apiVersion: v1
kind: ConfigMap
metadata:
  name: rfid-emu-service-configmap
  namespace: asset-spy
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_CONSUMER_PROPERTIES_BOOTSTRAP_SERVERS: "kafka:9092"